(function(root){
  "use strict";
  const TIME_ZONE=Intl.DateTimeFormat().resolvedOptions().timeZone||"America/Chicago";
  const BLOCK_SECONDS=3600;
  const DEFAULT_SPOT_SECONDS=60;
  function stationParts(date){const parts=new Intl.DateTimeFormat("en-US",{timeZone:TIME_ZONE,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(date);return Object.fromEntries(parts.filter(p=>p.type!=="literal").map(p=>[p.type,Number(p.value)]));}
  function zonedToUtc(year,month,day,hour=0,minute=0,second=0){const target=Date.UTC(year,month-1,day,hour,minute,second);let guess=target;for(let i=0;i<4;i++){const part=stationParts(new Date(guess));const represented=Date.UTC(part.year,part.month-1,part.day,part.hour,part.minute,part.second);guess+=target-represented;}return guess;}
  function dateKey(nowMs){const p=stationParts(new Date(nowMs));return `${p.year}-${String(p.month).padStart(2,"0")}-${String(p.day).padStart(2,"0")}`;}
  function hash(text){let value=2166136261;for(let i=0;i<text.length;i++)value=Math.imul(value^text.charCodeAt(i),16777619);return value>>>0;}
  function seededShuffle(items,seedText){const copy=items.slice();let seed=hash(seedText);const random=()=>{seed+=0x6D2B79F5;let v=seed;v=Math.imul(v^(v>>>15),v|1);v^=v+Math.imul(v^(v>>>7),v|61);return((v^(v>>>14))>>>0)/4294967296;};for(let i=copy.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
  function eligible(program){const runtime=Number(program&&program.runtimeSeconds);return Boolean(program&&program.cleared&&program.videoId&&Number.isFinite(runtime)&&runtime>=600);}
  function createDaySchedule(nowMs,catalog){const p=stationParts(new Date(nowMs));const midnightMs=zonedToUtc(p.year,p.month,p.day);const programs=(Array.isArray(catalog)?catalog:[]).filter(eligible);if(!programs.length)throw new Error("No Adventure TV programs are ready.");const key=dateKey(nowMs);const dayNumber=Math.floor(midnightMs/86400000);const cycle=seededShuffle(programs,`adventure-tv-week-${Math.floor(dayNumber/7)}`);const start=((dayNumber*7)%cycle.length+cycle.length)%cycle.length;return Array.from({length:24},(_,index)=>{const program=cycle[(start+index)%cycle.length];const startsAtMs=midnightMs+index*BLOCK_SECONDS*1000;return{id:`${key}-${String(index).padStart(2,"0")}`,movie:program,startsAtMs,endsAtMs:startsAtMs+BLOCK_SECONDS*1000,blockSeconds:BLOCK_SECONDS,fullStationSeconds:BLOCK_SECONDS};});}
  function createSegments(block,commercials){const runtime=Math.min(BLOCK_SECONDS,Math.max(600,Math.floor(Number(block.movie.runtimeSeconds)||3540)));const segments=[];let stationStart=0;const breakPoints=runtime>2800?[Math.min(1800,runtime-120)]:[];let sourceStart=0;breakPoints.concat([runtime]).forEach((boundary,index)=>{const duration=boundary-sourceStart;if(duration>0){segments.push({kind:"movie",title:block.movie.title,videoId:block.movie.videoId,cleared:true,sourceStart,stationStart,duration});stationStart+=duration;sourceStart=boundary;}if(index<breakPoints.length&&stationStart+DEFAULT_SPOT_SECONDS<BLOCK_SECONDS){const ad=(commercials||[])[index%(commercials||[]).length]||{};segments.push({kind:"commercial",title:ad.title||"Adventure intermission",videoId:ad.videoId||"",cleared:Boolean(ad.videoId&&ad.cleared),sourceStart:0,stationStart,duration:DEFAULT_SPOT_SECONDS});stationStart+=DEFAULT_SPOT_SECONDS;}});if(stationStart<BLOCK_SECONDS)segments.push({kind:"station",title:"Next adventure starts at the top of the hour",videoId:"",cleared:true,sourceStart:0,stationStart,duration:BLOCK_SECONDS-stationStart});return segments;}
  function resolve(nowMs,schedule,commercials){const block=schedule.find(item=>nowMs>=item.startsAtMs&&nowMs<item.endsAtMs)||schedule[schedule.length-1]||schedule[0];const blockElapsed=Math.max(0,Math.min(BLOCK_SECONDS-1,Math.floor((nowMs-block.startsAtMs)/1000)));const segments=createSegments(block,commercials);const segment=segments.find(item=>blockElapsed>=item.stationStart&&blockElapsed<item.stationStart+item.duration)||segments[segments.length-1];const segmentElapsed=Math.max(0,blockElapsed-segment.stationStart);return{block,segment,segmentElapsed,blockElapsed,mediaSeconds:segment.sourceStart+segmentElapsed,segmentRemaining:Math.max(0,segment.duration-segmentElapsed),movieReturnsIn:Math.max(0,segment.duration-segmentElapsed),blockRemaining:Math.max(0,BLOCK_SECONDS-blockElapsed)};}
  root.AdventureEngine={TIME_ZONE,BLOCK_SECONDS,stationParts,zonedToUtc,dateKey,createDaySchedule,createSegments,resolve};
})(window);
